name: lpf-ftp

services:
  lpf-db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - initdb:/docker-entrypoint-initdb.d
    networks:
      - lpf-ftpnet
  
  lpf-server:
    build:
      dockerfile: Dockerfile-server
    env_file: .env
    ports:
      - "${SERVER_INTERNAL_PORT}:${SERVER_PORT}"
    environment:
      - PORT=${SERVER_INTERNAL_PORT}
    volumes:
      - server-data:/app
    networks:
      - lpf-ftpnet
    depends_on:
      - lpf-db
  
  lpf-client:
    build:
      dockerfile: Dockerfile-client
    env_file: .env
    environment:
      - LPF_SERVER_ADDR=${SERVER_ADDR}
      - LPF_SERVER_PORT=${SERVER_PORT}
    volumes:
      - client-data:/app
    networks:
      - lpf-ftpnet
    tty: true
    stdin_open: true
    depends_on:
      - lpf-server


networks:
  lpf-ftpnet:


volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database/data'
  initdb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database/init'
  
  server-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './server-volume'
  
  client-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './'
