FROM alpine:latest

COPY ./include/LPTF_Net /source/include/LPTF_Net
COPY ./include/file_utils.hpp /source/include/file_utils.hpp
COPY ./include/client_actions.hpp /source/include/client_actions.hpp

COPY ./src/LPTF_Net /source/src/LPTF_Net
COPY ./src/file_utils.cpp /source/src/file_utils.cpp
COPY ./src/client_actions.cpp /source/src/client_actions.cpp

COPY ./src/client.cpp /source/src/client.cpp

COPY ./src/tests/unit_tests_client.cpp /source/src/tests/unit_tests_client.cpp

COPY ./Makefile /source

# install make, compiler and packages
# build libpqxx from https://github.com/jtv/libpqxx.git with cmake
# remove libpqxx source
# build lpf
# copy to /
# remove /source and packages
RUN apk update \
    && apk add --no-cache libstdc++ libgcc make g++ \
    build-base postgresql-dev cmake wget git \
    && git clone https://github.com/jtv/libpqxx.git /libpqxx && cd /libpqxx \
    && cmake -S . -B build && cmake --build build --target install \
    && cd .. && rm -rf /libpqxx \
    && make -C /source client \
    && cp /source/lpf /lpf \
    && make -C /source test_client \
    && cp /source/test /test \
    && rm -r /source \
    && apk del make g++ \
    build-base postgresql-dev cmake wget git

WORKDIR /app

# ENTRYPOINT ["/lpf"]

ENV LPF_SERVER_ADDR lpf-server
ENV LPF_SERVER_PORT 12345

COPY ./scripts/run_lpf_client.sh /run_lpf_client.sh
CMD ["sh", "/run_lpf_client.sh"]
