FROM alpine:latest

COPY ./include/LPTF_Net /source/include/LPTF_Net
COPY ./include/file_utils.hpp /source/include/file_utils.hpp
COPY ./include/logger.hpp /source/include/logger.hpp
COPY ./include/server_actions.hpp /source/include/server_actions.hpp

COPY ./src/LPTF_Net /source/src/LPTF_Net
COPY ./src/file_utils.cpp /source/src/file_utils.cpp
COPY ./src/logger.cpp /source/src/logger.cpp
COPY ./src/server_actions.cpp /source/src/server_actions.cpp

COPY ./src/server.cpp /source/src/server.cpp

COPY ./Makefile /source

RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    cmake \
    g++ \
    wget \
    git

RUN git clone https://github.com/jtv/libpqxx.git /libpqxx && \
    cd /libpqxx && \
    cmake -S . -B build && \
    cmake --build build --target install && \
    cd .. && rm -rf /libpqxx

# install make and compiler, build lpf_server, copy to /, remove /source and packages
RUN apk update \
    && apk add --no-cache libstdc++ libgcc make g++ \
    && make -C /source server \
    && cp /source/lpf_server /lpf_server \
    && make -C /source test_server \
    && cp /source/test /test \
    && rm -r /source \
    && apk del make g++

WORKDIR /app

ENV PORT 12345
EXPOSE 12345

CMD /lpf_server $PORT
