FROM alpine:latest

COPY ./include/LPTF_Net /source/include/LPTF_Net
COPY ./include/file_utils.hpp /source/include/file_utils.hpp
COPY ./include/logger.hpp /source/include/logger.hpp
COPY ./include/server_actions.hpp /source/include/server_actions.hpp

COPY ./src/LPTF_Net /source/src/LPTF_Net
COPY ./src/file_utils.cpp /source/src/file_utils.cpp
COPY ./src/logger.cpp /source/src/logger.cpp
COPY ./src/server_actions.cpp /source/src/server_actions.cpp

COPY ./src/server.cpp /source/src/server.cpp

COPY ./src/tests/unit_tests_server.cpp /source/src/tests/unit_tests_server.cpp

COPY ./Makefile /source

# install make, compiler and packages
# build libpqxx from https://github.com/jtv/libpqxx.git with cmake
# remove libpqxx source
# build lpf_server
# copy to /
# remove /source and packages
RUN apk update \
    && apk add --no-cache libstdc++ libgcc make g++ \
    build-base postgresql-dev cmake wget git \
    && git clone https://github.com/jtv/libpqxx.git /libpqxx && cd /libpqxx \
    && cmake -S . -B build && cmake --build build --target install \
    && cd .. && rm -rf /libpqxx \
    && make -C /source server \
    && cp /source/lpf_server /lpf_server \
    && make -C /source test_server \
    && cp /source/test /test \
    && rm -r /source \
    && apk del make g++ \
    build-base postgresql-dev cmake wget git

WORKDIR /app

ENV PORT 12345
EXPOSE 12345

CMD /lpf_server $PORT
