global:
  scrape_interval: 10s
  external_labels:
    monitor: dev        # name of monitoring
scrape_configs:
  # scrape our containers
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node'
    scrape_interval: 5s 
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'server'
    scrape_interval: 5s 
    static_configs:
      - targets: ['lpf-server:12345']
  - job_name: 'db'
    scrape_interval: 5s 
    static_configs:
      - targets: ['lpf-db:12345']